# Generated by Django 5.0.8 on 2024-09-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distance_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='restaurant_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Название ресторана'),
        ),
    ]
