# Generated by Django 5.0.8 on 2024-09-05 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distance_monitor', '0002_alter_location_restaurant_name'),
        ('foodcartapp', '0050_order_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='foodcartapp.order'),
        ),
    ]
