# Generated by Django 5.0.8 on 2024-09-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distance_monitor', '0003_alter_location_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=100, unique=True, verbose_name='Адрес'),
        ),
    ]
