# Generated by Django 3.2.15 on 2024-09-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distance_monitor', '0006_alter_location_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='order',
        ),
        migrations.RemoveField(
            model_name='location',
            name='restaurant_name',
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=100, unique=True, verbose_name='Адрес'),
        ),
    ]
