# Generated by Django 3.2.15 on 2024-09-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distance_monitor', '0007_auto_20240911_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Адрес'),
        ),
    ]
