# Generated by Django 3.2.15 on 2024-08-06 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0038_auto_20240806_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantmenuitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='foodcartapp.order', verbose_name='Зааказ'),
        ),
    ]
