# Generated by Django 3.2.15 on 2024-08-07 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_restaurantmenuitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='order',
        ),
        migrations.RemoveField(
            model_name='restaurantmenuitem',
            name='order',
        ),
    ]
