# Generated by Django 5.0.8 on 2024-08-26 04:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_alter_orderelements_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderelements',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена'),
        ),
    ]
