# Generated by Django 5.0.8 on 2024-09-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_alter_orderelements_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Необработанный', 'Необработанный'), ('Обрабатывается', 'Обрабатывается'), ('Готовится', 'Готовится'), ('Передан курьеру', 'Передан курьеру'), ('Доставлен', 'Доставлен')], db_index=True, default='Необработанный', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
