# Generated by Django 5.0.8 on 2024-09-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_order_called_at_order_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Наличными', 'Наличными'), ('Электронно', 'Электронно')], db_index=True, default='Электронно', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
